/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function linkFile(sourceCode: string, filename: string): string;
export interface Diagnostic {
  file?: string;
  message: string;
  code: number;
  start?: number;
  length?: number;
}
export interface CompileResult {
  code: string;
  diagnostics: Array<Diagnostic>;
}
export declare class Compiler {
  constructor();
  compile(filename: string, content: string): CompileResult;
  linkFile(filename: string, sourceCode: string): string;
}
