/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function linkFile(sourceCode: string, filename: string): string;
export declare class Compiler {
  constructor();
  compile(filename: string, content: string): string;
  constructor();
  compile(filename: string, content: string): string;
  linkFile(filename: string, sourceCode: string): string;
}
